# Generated by Django 4.2.7 on 2026-04-30 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_add_receita_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('moradia', 'Moradia'), ('mercado', 'Mercado'), ('restaurantes', 'Restaurantes / Delivery'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('contas', 'Contas e serviços'), ('compras', 'Compras'), ('outros', 'Outros')], max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='Categoria muito longa')]),
        ),
        migrations.CreateModel(
            name='MetaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('moradia', 'Moradia'), ('mercado', 'Mercado'), ('restaurantes', 'Restaurantes / Delivery'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('contas', 'Contas e serviços'), ('compras', 'Compras'), ('outros', 'Outros')], help_text='Null = meta geral (total do mês)', max_length=50, null=True)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(2)])),
                ('ano', models.PositiveSmallIntegerField()),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O valor da meta deve ser maior que zero')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Gasto',
                'verbose_name_plural': 'Metas de Gastos',
                'ordering': ['-ano', '-mes', 'categoria'],
                'unique_together': {('user', 'categoria', 'mes', 'ano')},
            },
        ),
    ]
