# Generated by Django 4.2.7 on 2026-05-04 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gasto_categoria_metagasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_competencia',
            field=models.DateField(blank=True, help_text='Mês de referência da receita (padrão: data do recebimento)', null=True),
        ),
        migrations.AlterField(
            model_name='metagasto',
            name='mes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
